version: '3.8'

services:
  frontend:
    build: frontend
    container_name: frontend-container
    ports:
      - 8080:8080
    depends_on:
      - backend

  backend:
    build: backend
    container_name: backend-container
    ports: 
      - 3000:3000
    # depends_on:
    #   - mongo

  # mongo:
  #   image: mongo # lastest version
  #   container_name: mongo-container
  #   ports: 
  #     - 27018:27017
  #   volumes:
  #     - './mongodb:/data/db'
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: zenfection

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express-container
  #   restart: always
  #   ports:
  #     - 8082:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: zenfection
  #     ME_CONFIG_MONGODB_URL: mongodb://root:zenfection@mongo:27017/

#* command: docker-compose -f docker-compose.yml up -d