/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CartMenu: typeof import('./components/header/CartMenu.vue')['default']
    Category: typeof import('./components/home/Category.vue')['default']
    Copyright: typeof import('./components/footer/bottom/Copyright.vue')['default']
    Feature: typeof import('./components/footer/top/Feature.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FooterBottom: typeof import('./components/footer/FooterBottom.vue')['default']
    FooterTop: typeof import('./components/footer/FooterTop.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HeroIntro: typeof import('./components/home/HeroIntro.vue')['default']
    Logo: typeof import('./components/header/Logo.vue')['default']
    Mobile: typeof import('./components/header/cart/Mobile.vue')['default']
    MobileReponsitive: typeof import('./components/header/MobileReponsitive.vue')['default']
    NavMenu: typeof import('./components/header/NavMenu.vue')['default']
    Payment: typeof import('./components/footer/bottom/Payment.vue')['default']
    Product: typeof import('./components/header/cart/Product.vue')['default']
    ProductFeature: typeof import('./components/home/ProductFeature.vue')['default']
    QuickAction: typeof import('./components/footer/top/QuickAction.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/header/Search.vue')['default']
    Slider: typeof import('./components/home/Slider.vue')['default']
    SocialLink: typeof import('./components/footer/top/SocialLink.vue')['default']
    Support: typeof import('./components/footer/top/Support.vue')['default']
    UserMenu: typeof import('./components/header/UserMenu.vue')['default']
  }
}
